// <auto-generated />
using System;
using KocurmeApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KocurmeApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028102419_Contingents")]
    partial class Contingents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KocurmeApp.Domain.Entities.CheatingStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BAL1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BAL2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("BINA")
                        .HasColumnType("smallint");

                    b.Property<byte>("EYNI_B")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EYNI_D")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EYNI_Y")
                        .HasColumnType("tinyint");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<byte>("FENN")
                        .HasColumnType("tinyint");

                    b.Property<string>("FNADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IMT_GUN")
                        .HasColumnType("tinyint");

                    b.Property<int>("IS_N1")
                        .HasColumnType("int");

                    b.Property<int>("IS_N2")
                        .HasColumnType("int");

                    b.Property<decimal>("T_OXSHAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("V_BINA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Y_OXSHAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("ZAL1")
                        .HasColumnType("smallint");

                    b.Property<short>("ZAL2")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("CheatingStudents");
                });

            modelBuilder.Entity("KocurmeApp.Domain.Entities.Contingent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("IMT_GUN")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("IMT_YERI")
                        .HasColumnType("tinyint");

                    b.Property<string>("IZAHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("NUM_K")
                        .HasColumnType("tinyint");

                    b.Property<short?>("SAYI")
                        .HasColumnType("smallint");

                    b.Property<string>("SAYI0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("SEC")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TIP_OTUR")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("YASH_KATEQ")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Contingents");
                });

            modelBuilder.Entity("KocurmeApp.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("KocurmeApp.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("B_KOD")
                        .HasColumnType("smallint");

                    b.Property<byte>("DIL")
                        .HasColumnType("tinyint");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("GR_FL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IMT_YERI")
                        .HasColumnType("tinyint");

                    b.Property<string>("INDMEKTEB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("KOL_ABT")
                        .HasColumnType("tinyint");

                    b.Property<byte>("KOL_NAZ")
                        .HasColumnType("tinyint");

                    b.Property<byte>("KOL_SIRA")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOL_SIRA0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("KOL_YER")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOL_YER0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MEKT_KOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("MERTEBE")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MODUL")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("NUMMETN")
                        .HasColumnType("tinyint");

                    b.Property<string>("OK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEKTEK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TUTUMU")
                        .HasColumnType("tinyint");

                    b.Property<string>("TUTUMU0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_BINA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("XAR_DIL")
                        .HasColumnType("tinyint");

                    b.Property<string>("YASHKATEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Z_KOD")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("KocurmeApp.Domain.Entities.CheatingStudent", b =>
                {
                    b.HasOne("KocurmeApp.Domain.Entities.Exam", "Exam")
                        .WithMany("CheatingStudents")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("KocurmeApp.Domain.Entities.Room", b =>
                {
                    b.HasOne("KocurmeApp.Domain.Entities.Exam", "Exam")
                        .WithMany("Rooms")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("KocurmeApp.Domain.Entities.Exam", b =>
                {
                    b.Navigation("CheatingStudents");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
